# run: ansible-playbook playbook.yml -i inventory/hosts
- hosts: all
  user: centos
  become: yes
  vars:
    hostname: oliver-vm-test
    domain_name: sa.cs.ut.ee
    ip_address: 172.17.88.253
    ip_last_octet: 253
    reverse_zone_name: 88.17.172.in-addr.arpa

  roles:
  - { role: etais, tags: etais }
  - { role: firewall, tags: firewall }
  - { role: DNS, tags: DNS }
