# run: ansible-playbook playbook.yml -i inventory/hosts
- hosts: all
  user: centos
  become: yes
  vars:
    hostname: oliver-vm
    domain_name: sa.cs.ut.ee
    ip_address: 172.17.88.221
    ip_last_octet: 221
    reverse_zone_name: 88.17.172.in-addr.arpa

  roles:
  - etais
  - firewall
  - DNS
  - web_services
  - mail
