- name: Open necessary ports in firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 53/tcp
    - 53/udp
    - 8301/udp
    - 8301/tcp

- name: Reload firewalld to apply changes
  command: firewall-cmd --reload
